In [59]:
import pandas as pd
#gps_data_path="/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/08_Fieldwork/07_GPS tracking/Selbourne reports/"
gps_data_path="/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/08_Fieldwork/07_GPS tracking/Sakubvha reports/"

#selborne records

d7_sel = "device_7/HTK913-04633-History+route+details.xlsx"
d3_sel = "device_3/HTK913-04697-History+route+details.xlsx"
d5_sel = "device_5/HTK913-77711-History+route+details.xlsx"
d1_sel = "device_1/HTK913-04612-History+route+details.xlsx"
d6_sel = "device_6/HTK913-04609-History+route+details.xlsx"
d2_sel = "device_2/HTK913-04624-History+route+details.xlsx"
d12_sel = "device_12/HTK913-62682-History+route+details.xlsx"
d4_sel = "device_4/HTK913-04586-History+route+details.xlsx"
d10_sel = "device_10/HTK913-04549-History+route+details.xlsx"
d8_sel = "device_8/HTK913-04501-History+route+details.xlsx"
d9_sel = "device_9/HTK913-62966-History+route+details.xlsx"

#sakubvha records
d13_sak = "device_13/HTK913-62754-History+route+details.xlsx"
d14_sak = "device_14/HTK913-62847-History+route+details.xlsx"
d15_sak = "device_15/HTK913-62792-History+route+details.xlsx"
d16_sak = "device_16/HTK913-62394-History+route+details.xlsx"
d17_sak = "device_17/HTK913-62884-History+route+details.xlsx"
d18_sak = "device_18/HTK913-62912-History+route+details.xlsx"
d19_sak = "device_19/HTK913-62492-History+route+details.xlsx"

## these two below got a bit messed up
d3_sak = "device_r_i21_3/HTK913-04697-History+route+details.xlsx"
d9_sak = "device_r_i22_6_9/HTK913-62966-01July-2July.xlsx"
# Import as df
df=pd.read_excel(gps_data_path+d9_sak, skiprows=2)
df.head()

   No.       Position time       Lat       Lon  Speed  Direction Track way
0    1 2023-06-27 08:47:59 -18.97622  32.66949    0.0          0       GPS
1    2 2023-06-27 08:48:04 -18.97622  32.66949    0.0          0       GPS
2    3 2023-06-27 08:49:04 -18.97639  32.66913    0.0        263       GPS
3    4 2023-06-27 08:51:04 -18.97624  32.66963    0.0         49       GPS
4    5 2023-06-27 08:52:04 -18.97656  32.66932    0.0         78       GPS

In [60]:
# Sort DataFrame based on timestamps (if necessary)
df= df.sort_values(by= 'Position time')

# Calculate the time interval between consecutive timestamps
df['time_interval'] = df['Position time'].diff()

# Display DataFrame with time intervals
#print(df)

#create a subset dataframe of locations where the individual stopped for 30 minutes or longer
stoppoints = df[df['time_interval'] >= pd.Timedelta(minutes=30)]
print(stoppoints)

#export that subset of points
stoppoints.to_csv(gps_data_path+"device_r_i22_6_9/"+"sak_9.csv", index=False, columns=df.columns[1:])

       No.       Position time       Lat       Lon  Speed  Direction  \
46      47 2023-06-27 11:12:30 -18.98496  32.67254   0.00        268
49      50 2023-06-27 13:11:41 -18.98521  32.67253   0.00        120
51      52 2023-06-27 14:14:32 -18.98510  32.67256   3.70        177
302    303 2023-06-27 19:20:35 -18.98369  32.66016  20.37        160
324    325 2023-06-28 04:31:18 -18.99260  32.63876  14.81          0
485    486 2023-06-28 09:22:22 -18.98498  32.67250   5.55        225
492    493 2023-06-28 11:44:00 -18.98491  32.67253   5.55          0
498    499 2023-06-28 12:34:03 -18.98492  32.67255   3.70        272
500    501 2023-06-28 14:57:19 -18.98505  32.67260   3.70        239
722    723 2023-06-29 04:39:49 -18.99287  32.63830   7.40        166
963    964 2023-06-29 11:24:47 -18.99254  32.63877   3.70        176
965    966 2023-06-29 12:11:27 -18.99286  32.63828   0.00        180
1019  1020 2023-06-29 14:13:41 -18.98514  32.67245   0.00        234
1209  1210 2023-06-29 18:06:42 -19.01327  32.61791   0.00        126
1232  1233 2023-06-30 04:35:08 -18.99271  32.63833   0.00        247
1301  1302 2023-06-30 06:37:08 -18.99656  32.62000  51.85        321
1401  1402 2023-06-30 08:52:40 -18.99267  32.63868   3.70        244
1449  1450 2023-06-30 15:18:20 -18.99771  32.62088   3.70        348

     Track way   time_interval
46         GPS 0 days 00:49:50
49         GPS 0 days 01:35:11
51         GPS 0 days 00:37:51
302        GPS 0 days 00:37:20
324        GPS 0 days 08:49:39
485        GPS 0 days 01:12:41
492        GPS 0 days 01:36:38
498        GPS 0 days 00:31:41
500        GPS 0 days 02:22:16
722        GPS 0 days 09:48:29
963        GPS 0 days 01:49:04
965        GPS 0 days 00:45:56
1019       GPS 0 days 00:59:25
1209       GPS 0 days 00:31:59
1232       GPS 0 days 10:06:26
1301       GPS 0 days 00:36:59
1401       GPS 0 days 00:34:32
1449       GPS 0 days 05:16:13